
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_training_nov2025'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_training_nov2025'


model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name STRING, run_start_timestamp TIMESTAMP, run_end_timestamp TIMESTAMP )"
  - "INSERT INTO {{ target.schema }}.audit_log VALUES ('dbt_project', CURRENT_TIMESTAMP,NULL)"

on-run-end:
  - "INSERT INTO {{ target.schema }}.audit_log VALUES ('dbt_project', NULL,CURRENT_TIMESTAMP)"
  

models:
  dbt_training_nov2025:
    +pre-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP,NULL)"
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}',NULL,CURRENT_TIMESTAMP)"
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: view
    gold_airbnb:
      +schema: 'gold_airbnb'
      +materialized: view
    platinum_airbnb:
      +schema: 'platinum_airbnb'
      +materialized: view
vars:
  dbt_user_name: "Ankur from Project yml"